### ISSUE TITLE
Peek 3.0?

### ISSUE THREAD

**Issue by mshibanami** [shaps80/Peek#19]
Hi.

The latest version of the podspec of Peek is 2.3.
https://github.com/CocoaPods/Specs/blob/master/Specs/9/0/c/Peek/2.3/Peek.podspec.json

But current `master` is 3.0.
When do you upgrade it to 3.0 officially?

Thanks.

**Comment by shaps80** [comment]
Swift 3/4+ removed some of the features I relied upon for Peek to work. So atm I'm unable to support this, which is the only reason I haven't updated. 

I have considered porting much of the implementation _back_ to Objective-C so that I would no longer have this issue, but its a bit of work that I don't have time for atm.

Sorry.

**Comment by shaps80** [comment]
@mshibanami Swift 4 will be officially supported this week!

Thank you for supporting the project.
