### ISSUE TITLE
Generate JSON from Controller/Views Hierarchy

### ISSUE THREAD

**Issue by shaps80** [shaps80/Peek#32]
Starting from the `peekingWindow` this should walk up the hierarchy and generate a JSON snapshot of the entire `UIViewController` and `UIView` hierarchy so we can add it as an option to a Report.

This ticket includes the task of adding another Report option for including this JSON as a part of the Report sharing.

**Comment by Chris-Corea** [comment]
Hello!

I think this project is awesome and thought I could help out with this. I've been playing with the code a bit and I think I've got a pretty good idea of how to get a JSON formatted String out with the report. 

It's easy enough to add the new Report option; basically just creating another boolean in Report.swift to configure the setting and the associated tableview cell, switch, and handler in ReportViewController.swift. 

As for building out the string, I could traverse the view stack like a tree (recursively) and build out a JSON object as I go. I'd add this to the UIView+Extension file so that every UIView could provide a JSON formatted String of its hierarchy. 

Thoughts? Your contribution.md file mentioned that non-trivial changes should be discussed first. I'm thinking this is a non-trivial change so I wanted to run it by you first.

**Comment by shaps80** [comment]
@Chris-Corea glad you like it.

Yeah, I'd love to get this feature in.
Just a couple of thoughts:

I already walk the hierarchy to determine which views to surface in the Overlay. I wonder if you could actually just piggy-back on this and build a tree-model struct that represents the current hierarchy.

I'd prefer this approach as I have some other ideas for the future that would benefit from such a representation. I don't think this is a huge amount of work, and happy to discuss any issues, considerations you may have?

**Comment by Chris-Corea** [comment]
All right, that all sounds good. I think the bit I'm struggling with though is how to accurately represent the view hierarchy as an array. The `parseView(:)` function works well enough to create the array, but the array loses the parent-child relationship between views. Even in the sample app packaged with Peek, the "View Hierarchy" option in the inspector shows sibling views as subviews in its tree structure (attaching a screenshot). Food for thought, I guess.

I'll work on getting that ViewModel struct set up using the `parseView` method!
<img width="400" alt="screen shot 2018-05-04 at 11 26 03 am" src="https://user-images.githubusercontent.com/1231808/39646003-ddaea18c-4f8e-11e8-8ac6-1a1a947d0b79.png">

**Comment by shaps80** [comment]
Oh good find. That’s actually a layout/tab bug. I need to fix that... 

But you’re right the requirements for that function are a little different to your own. But I’m just wondering if you can piggy back on the same iterations just so we don’t duplicate effort. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shaps80** [comment]
Those are not sibling views. You selected the text view and now it’s showing 3 subviews which represent the two images (scroll bars) as well as the content view for the text. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shaps80** [comment]
Either way I’d just like to avoid duplicated effort — but happy for you to do what you think is right and then we can review it on a PR. Sound good @Chris-Corea ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
