### ISSUE TITLE
Missing Swift Language Version on Build settings Pod

### ISSUE THREAD

**Issue by cjimenezpacho** [shaps80/Peek#60]
Hi!
I have peek module to my objective c app using cocoapods but when I try to build I receive this output:

`The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.`

I've added SWIFT_VERSION = 4 (and tried 3.2) as User-Defined Build Setting to my target but I have the same output.
Also I have changed Swift Language Version on Build Settings of the pod to 4.0 (It was Unspecified):

![snap-1](https://user-images.githubusercontent.com/2428271/39465682-ee554b92-4d24-11e8-8cbe-0cddf812f2ea.png)

It seems work but I can't use peek because when I add to my AppDelegate I receive this output:

![snap-2](https://user-images.githubusercontent.com/2428271/39465718-21496218-4d25-11e8-8c8c-5effb2a0bce0.png)

Can I use it on a Obj-C project?

Regards!

**Comment by shaps80** [comment]
Obj-C support has always been included, however in Swift 4 it's now required that all accessible function are explicit prefixed with `@objc` – a PR was recently raised that included this but it hasn't been included in a release just yet since the PR couldn't be merged. I will ensure this is included in the next release. I'll keep this issue open until then and let you know.

Thanks.

**Comment by shaps80** [comment]
**Update**: Unfortunately there's no setting I can set in the pod spec to force the Swift version, however 4.0 is required. There is a known issue in Cocoapods that is included I believe in a recent beta, so hopefully this will be fixed in future updates.

For now, you can add this to your `Podfile` so you don't have to manually configure the Build Settings all the time:

```ruby
  post_install do |installer|
    installer.pods_project.targets.each do |target|
       if target.name == "Peek" then
         target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
       end
    end
  end
```

**Comment by shaps80** [comment]
@cjimenezpacho just following up, did this resolve your issue?

**Comment by shaps80** [comment]
Closing since this ticket hasn't had any updates. Other projects have reported this working fine.
