### ISSUE TITLE
[Feature request] Add lightweight logging capability

### ISSUE THREAD

**Issue by josefdolezal** [shaps80/Peek#62]
Hey @shaps80! Thanks for an amazing library, it's 💯💯!

#### Context
I would like to propose new feature - a simple logging framework. Currently there are few in-app logging frameworks like [Dotzu](https://github.com/remirobert/Dotzu) but most of them seems to be inactive for quite a long time now (Dotzu since Sep 2017).

This feature would add possibility to create & preview logs collected during app runtime. These would be categorised using its severity (error, warning, info, ...) with possibility to add meta data (like network call response).

Simple use case may be as follows. The app is being tested and there is an unexpected error during network request. The app shows this nice pop saying "Hey, some error occurred during doing this and that.". Tester will take a screenshot and fill a bug report. However the information about what exactly went wrong may be lost.

With this feature, tester may attach a log message while creating a bug report.

Another simple yet powerful feature is debugging. The app would provide view with list of the latest log messages so user can inspect what the app is doing under the hood without Xcode.

#### Library design impact
I am not sure if this propose fits design goals of Peek since the library is more related to the app UI.
New API exposed by Peek would look like `Peek.log(message: "", severity: .error)`. In code, this:

```swift
guard let `self` = self else {
    // Should not happen
    return
}
```

would become this:

```swift
guard let `self` = self else {
    Peek.log(message: "My message", severity: .error)
    return
}
```

I would like to hear your opinion on that. Also, I am open on getting involved into implementation. Thank you!

**Comment by shaps80** [comment]
@josefdolezal thanks for getting in touch.

I have considered something like this.

Could you elaborate on the type of logging you would expect? Also I'm not sure I understand what you mean by "add more context to reported screens"

**Comment by josefdolezal** [comment]
Thank you for quick response!

I've updated my first post so it's all together.

**Comment by shaps80** [comment]
Ahh ok I think understand what you mean. 

So Peek is primarily an inspection tool, rather than a debugging tool. I have considered previously whether or not Peek could be more of a dashboard for various tools but my main concern is keeping Peek lightweight, focused and with a very small runtime-footprint.

This kinda sounds more like a debugging and bug-reporting tool – in which case there are various other frameworks you can integrate with that even have server side logging for consolidated logs, etc... which IMHO is a lot more useful than on device.

I can see a little bit of value, so if you want to try and convince me further I'm totally open to it, but I wouldn't want to waste any of your time on something that personally I feel is a little out of scope for what Peek is as a product.

**Comment by josefdolezal** [comment]
Hey @shaps80, sorry for late reply!

No problemo, thats why I asked in the first place! I agree with you that the runtime-footprint should be as small as possible. This could be done using some plugins API (maybe  related to #29?) though so Peek would still be "just" inspection tool but extendible to do more if user needs it.

I will close the issue for now and will let you know if I come up with solution that will fit Peek's API design better.

Thank you for your time & review!
