### ISSUE TITLE
Example app: Nothing happens when running on iPhone 8 iOS 11.2.5, from Xcode 10.

### ISSUE THREAD

**Issue by Sajjon** [shaps80/Peek#64]
When I shake the device I see that the `motionBegan` gets called, and I set a break point inside `Peek` method `handleShake` I see that it gets called, but nothing happens.

What did I do wrong? :)

**Comment by shaps80** [comment]
Check the view hierarchy in your app? Perhaps Peek isn't discovering the correct Window, it might be being presented underneath? Also check your Console, if Peek couldn't be presented, usually UIKit would log something important about it. Hope that's helpful.

**Comment by mshibanami** [comment]
On a physical device, the example app allows you to launch Peek with volume controls rather than shake gestures, because of [`options.activationMode = .auto`](https://github.com/shaps80/Peek/blob/master/Example/NotTwitter/AppDelegate.swift#L22).
FYI, that documentation comment is here:
https://github.com/shaps80/Peek/blob/42ef551537f60384de5e7e70d9fd2947818e2c82/Pod/Classes/PeekOptions.swift#L25-L31

It seems this specification deserves to be written on README or something like that, btw.

**Comment by shaps80** [comment]
That’s right. And it is in the readme, above that mention that the simulator is the exception/caveat which required a shake gesture instead 😬

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
