### ISSUE TITLE
Any way to select parent views?

### ISSUE THREAD

**Issue by nextriot** [shaps80/Peek#9]
This looks fantastic! Thanks for making this available to us.

From my limited amount of play I havent been able to find a way to select parent elements e.g.

![screen shot 2016-04-22 at 18 53 46](https://cloud.githubusercontent.com/assets/711457/14755897/e24fc7c8-08bb-11e6-9f17-03ba79f75ec3.png)

In the screenshot, I've embedded a label within a child view & another label within its sub view. However, I'm not able to tap or drag on either of the views, only the labels.

Any ideas?

**Comment by shaps80** [comment]
By default, peek tries to remove views you probably don't care about. 

One of the rules it apples to handle this is ignoring views that are purely containers -- which is why you are unable to select the parent in these cases. 

This weekend I am releasing an update, one of which allows you to provide overrides for these kinds of options. So if you can wait a day or two, it'll be available to you shortly ;)

In 99% of the apps we tested, selecting the parent wasn't of value, since its generally a pure UIView, with little information we care about.

Another update which I hope to release this weekend, provides auto layout and layout-between-two-views overlays. This is where disabling this kind of feature becomes more valuable I think.

So in the next version you can do something similar to this:

```swift
window?.peek.enableWithOptions { options in 
  options.ignoreContainers = false
}
```

**Comment by shaps80** [comment]
quick note, in the current version, if you make your containers a subclass of UIView, they will then be selectable :)

**Comment by shaps80** [comment]
ok, so you run `pod update` and the latest version of Peek should fix your issue :)

**Comment by nextriot** [comment]
Thanks for the speedy response. Indeed, subclassing did the trick.

Great library. Looking forward to the update ;)

**Comment by shaps80** [comment]
2.0.1 included the changes you needed. ReadMe updated and the demo app too so you can see how ;-) 

Enjoy, feedback appreciated.

**Comment by nextriot** [comment]
Perfect! Thanks again Shaps.
